stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Build started"
    - mkdir build
    - g++ src/main.cpp src/save.cpp src/config.cpp src/compare.cpp -o build/codeDiff
    - echo "Build ended"
    - mkdir test
    - touch test/testFile.txt
    - echo "hello" >> test/testFile.txt
  artifacts:
    paths:
      - build/
test:
  stage: test
  script:
    - echo "Testing"
    - echo "Help see,,,"
    - build/codeDiff
    - echo "save..."
    - build/codeDiff save test/testFile.txt test.txt
    - echo "compare..."
    - echo "hello x2" >> test/testFile.txt
    - build/codeDiff compare test/testFile.txt test.txt
    - rm test/testFile.txt
